[package]
name = "genevo"
version = "0.1.4"
authors = ["haraldmaida"]
license = "MIT/Apache-2.0"
description = """
genevo provides building blocks to run simulations of optimization and search problems using
genetic algorithms (GA).

Execute genetic algorithm (GA) simulations in a customizable and extensible way.
"""
keywords = ["genetic", "evolutionary", "algorithm"]
repository = "https://github.com/innoave/genevo"
documentation = "https://docs.rs/genevo"
#homepage = "https://innoave.github.io/genevo"
readme = "README.md"

edition = "2018"

[dependencies]
chrono = "0.4"
fixedbitset = "0.1"
log = "0.4"
rand = "0.6"
rand_xoshiro = "0.2"
rayon = "1.0"

[dev-dependencies]
criterion = { version = "0.2", default-features = false }
galvanic-assert = "0.8"
quickcheck = "0.8"
#log4rs = "0.8"

[lib]
bench = false

[[bench]]
name = "index_of_value_in_vector"
harness = false

[[example]]
name = "monkeys"
path = "examples/monkeys/main.rs"

[[example]]
name = "queens"
path = "examples/queens/main.rs"
