[package]
name = "genevo"
version = "0.1.0"
authors = ["haraldmaida <harald.maida@innoave.com>"]
license = "MIT/Apache-2.0"
description = "Implements genetic algorithm (GA) simulations in a customizable and extensible way"
keywords = ["genetic", "evolutionary", "algorithm"]

repository = "https://github.com/innoave/genevo"
documentation = "https://docs.rs/genevo"
readme = "README.md"

[lib]
name = "genevo"
path = "src/lib.rs"

[dependencies]
chrono = "^0.3"
jobsteal = "^0.5"
log = "*"
rand = "*"

[dev-dependencies]
quickcheck = "*"
hamcrest = "*"
log4rs = "*"
