[package]
name = "genevo"
version = "0.0.1"
authors = ["haraldmaida <harald.maida@innoave.com>"]
license = "MIT/Apache-2.0"
description = """
genevo provides building blocks to run simulations of optimization and search problems using
genetic algorithms (GA).

Execute genetic algorithm (GA) simulations in a customizable and extensible way.
"""
keywords = ["genetic", "evolutionary", "algorithm"]

repository = "https://github.com/innoave/genevo"
documentation = "https://docs.rs/genevo"
#homepage = "https://innoave.github.id/genevo"
readme = "README.md"

[lib]
name = "genevo"
path = "src/lib.rs"

[dependencies]
fixedbitset = "*"
chrono = "*"
log = "*"
rand = "*"
rayon = "*"

[dev-dependencies]
quickcheck = "*"
hamcrest = "*"
#log4rs = "*"

[[example]]
name = "monkeys"
path = "examples/monkeys/main.rs"

[[example]]
name = "queens"
path = "examples/queens/main.rs"
