[package]
name = "genevo"
version = "0.1.0"
authors = ["haraldmaida <harald.maida@innoave.com>"]
description = "Execute genetic algorithm (GA) simulations in a customizable and extensible way"
keywords = ["genetic", "evolutionary", "algorithm"]

homepage = "https://github.com/innoave/genevo"
documentation = "https://docs.rs/genevo"
repository = "https://github.com/innoave/genevo"

license = "MIT/Apache-2.0"
readme = "README.md"

[lib]
name = "genevo"
path = "src/lib.rs"

[dependencies]
chrono = "*"
clap = "*"
futures = "*"
log = "*"
rand = "*"

[dev-dependencies]
quickcheck = "*"
hamcrest = "*"
log4rs = "*"
